In [1]:
from PIL import Image
import numpy as np

In [3]:
im=np.array(Image.open("img/1.jpg"))
im.shape

(640, 1024, 3)

In [4]:
im1=np.array(Image.open("img/2.jpg"))
im1.shape

(340, 600, 3)

In [5]:
#convert image to grayscale
im_gray=np.array(Image.open("img/1.jpg").convert("L"))

In [6]:
#saving image
data=Image.fromarray(im_gray)
data.save("img/1n.jpg")


In [8]:
#changing the colors of picture
im
for i in range(120,160,1):
    im[i]=45
newimage=Image.fromarray(im)
newimage.save("img/1nn.jpg")

In [9]:
#concatenation of images
im1=np.array(Image.open("img/1.jpg"))
im1_r=im1.copy()
im1_g=im1.copy()
im1_b=im1.copy()
#RGB
im1_r[:,:,(1,2)]=0
im1_g[:,:,(0,2)]=0
im1_b[:,:,(0,1)]=0

In [10]:
#concatenate
im_news=np.concatenate((im1_r,im1_g,im1_b),axis=1)
n1=Image.fromarray(im_news)
n1.save("img/q.jpg")

In [12]:
#vstack
im_news=np.vstack((im1_r,im1_g,im1_b))
n1=Image.fromarray(im_news)
n1.save("img/q3.jpg")

In [13]:
im=np.array(Image.open("img/1.jpg"))
im1=np.array(Image.open("img/2.jpg"))

In [32]:
im[20:80,5,1]=im1[280:340,5,1]


In [33]:
im.shape

(640, 1024, 3)

In [34]:
data=Image.fromarray(im)
data.save("img/1q.jpg")

In [38]:
im
im1
for i in range(160,1,1):
    im[i]=im1[i]
    
newimage=Image.fromarray(im)
newimage.save("img/1w.jpg")

In [48]:
im[0:1000,1,1]


array([131, 132, 132, 132, 132, 133, 133, 133, 135, 134, 132, 131, 131,
       131, 132, 133, 133, 132, 132, 131, 131, 132, 132, 133, 131, 133,
       134, 136, 135, 135, 135, 135, 138, 137, 136, 135, 134, 135, 135,
       134, 136, 136, 135, 135, 135, 136, 136, 136, 137, 138, 138, 138,
       139, 140, 142, 145, 142, 141, 139, 141, 143, 145, 147, 146, 145,
       144, 142, 142, 144, 144, 143, 142, 139, 140, 141, 140, 140, 140,
       140, 141, 141, 142, 142, 143, 144, 144, 143, 142, 142, 143, 145,
       144, 143, 141, 143, 144, 144, 146, 144, 143, 144, 141, 145, 157,
       173, 164, 169, 167, 152, 155, 177, 188, 173, 153, 152, 150, 149,
       153, 143, 143, 145, 144, 144, 148, 160, 171, 171, 165, 156, 153,
       150, 151, 151, 149, 148, 149, 143, 143, 144, 144, 144, 144, 144,
       144, 142, 141, 143, 145, 147, 149, 154, 158, 187, 215, 212, 167,
       137, 145, 153, 146, 151, 150, 149, 149, 149, 149, 150, 153, 157,
       154, 153, 154, 153, 150, 149, 149, 155, 153, 154, 156, 15

In [47]:
im1[0:1000,1,1]

array([131, 132, 132, 132, 132, 133, 133, 133, 156, 164, 152, 154, 173,
       177, 152, 176, 180, 179, 190, 190, 187, 194, 193, 191, 188, 187,
       166, 159, 168, 172, 166, 145, 180, 195, 175, 144, 164, 177, 178,
       163, 182, 176, 173, 157, 177, 166, 162, 142, 126, 121, 142, 128,
       137, 142, 137, 149, 140, 134, 119, 139, 142, 144, 176, 167, 170,
       170, 172, 174, 173, 171, 171, 172, 177, 187, 182, 183, 189, 176,
       156, 136, 133, 140, 125, 126, 134, 127, 133, 151, 160, 148, 143,
       137, 132, 131, 126, 126, 126, 132, 128, 126, 115, 130, 131, 127,
       135, 141, 126, 120, 118, 112, 117, 131, 115, 113, 110, 118, 115,
       107, 115, 118, 118, 117, 105, 111, 104, 116, 100, 111, 116, 127,
       113,  92, 104, 109, 118, 110, 107, 106, 109, 116, 121, 125, 122,
       111, 109, 103, 102, 110, 125, 126, 118, 128, 103, 119,  98, 109,
       121, 101, 105, 115,  98, 109, 106, 104,  97,  84,  86,  91,  96,
       100, 110, 125, 139, 112, 104, 104, 118, 111, 107, 100,  9

In [54]:
im2=im1
im2[0:340,1,1]=0


In [68]:
im2
for i in range(340,340,1):
    im2[i]=45
    
im2[0:340,1,1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [69]:
newimage=Image.fromarray(im2)
newimage.save("img/23.jpg")

In [90]:
im2=np.array(Image.open("img/1.jpg"))
im=np.array(Image.open("img/2.jpg"))

In [78]:
im2.shape


(640, 1024)

In [91]:
im3=im2[0:340,0:600]

In [96]:
im.shape

(340, 600, 3)

In [88]:
im3.shape

(340, 600)

In [92]:
im3
for i in range(120,240,1):
    im3[i]=im[i]
newimage=Image.fromarray(im3)
newimage.save("img/23.jpg")

In [93]:
im4=np.array(Image.open("img/3.jpg"))

In [94]:
im4.shape

(900, 1600, 3)

In [100]:
im5=im4[0:340,0:600]

In [101]:
im5
for i in range(120,240,1):
    im5[i]=im[i]
newimage=Image.fromarray(im5)
newimage.save("img/24.jpg")

In [102]:
im5.shape

(340, 600, 3)

In [105]:
im5[120:,240:,1]=im2[0:220,0:360,1]

In [106]:
newimage=Image.fromarray(im5)
newimage.save("img/25.jpg")

In [107]:
#concatenate
im_news=np.concatenate((im,im1,im4),axis=1)
n1=Image.fromarray(im_news)
n1.save("img/new.jpg")

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 340 and the array at index 2 has size 900

In [109]:
print(im.shape)
print(im1.shape)
print(im4.shape)

(340, 600, 3)
(340, 600, 3)
(900, 1600, 3)


In [110]:
im4=im4[0:340,0:600,0:]

In [111]:
im4.shape

(340, 600, 3)

In [112]:
#concatenate
im_news=np.concatenate((im,im1,im4),axis=1)
n1=Image.fromarray(im_news)
n1.save("img/new.jpg")

In [131]:
im2=np.array(Image.open("img/1.jpg"))
im=np.array(Image.open("img/2.jpg"))
im4=np.array(Image.open("img/3.jpg"))


In [114]:
print(im.shape)
print(im2.shape)
print(im4.shape)

(340, 600, 3)
(640, 1024, 3)
(900, 1600, 3)


In [115]:
im4=im4[0:340,0:600,0:]
im2=im2[0:340,0:600,0:]

In [116]:
print(im.shape)
print(im2.shape)
print(im4.shape)

(340, 600, 3)
(340, 600, 3)
(340, 600, 3)


In [118]:
#concatenate
im_news=np.concatenate((im,im2,im4),axis=1)
n1=Image.fromarray(im_news)
n1.save("img/new.jpg")

In [ ]:

from  PIL import Image 
import numpy as np
 
im = np.array(Image.open("img_tiger.jpg"))
 
im.shape
 
#grey image
im_gray = np.array(Image.open("img_tiger.jpg").convert("L"))
 
data = Image.fromarray(im_gray) 
data.save("img_tiger_grey.jpg") 
 
#chanages are not allowed
im1 = np.array(Image.open("img_ganesha.jpg"))
print(type(im1))
 
im1.flags.writeable
astype
 
#changing the colors of the pic
 
for i in range(120,160,1):
    im1[i]= 45
    im1[0,1,1]=0
    im1[0,100]=0
    im1[1,100]=0
 
newimage=Image.fromarray(im1)
print(newimage)
newimage.mode
newimage.save("img_ganesha_change.jpg")
 
 
 
#Get the pixel values and set them
t= im[90,190]
t
 
print(im[90,190,2])
 
#concatenation of images
im1 = np.array(Image.open("img_ganesha.jpg"))
im_r = im1.copy()
im_g=im1.copy()
im_b=im1.copy()
#RGB
im_r[:,:, (1,2)]=0
im_g[:,:, (0,2)]=0
im_b[:,:, (0,1)]=0
 
 
#im_new = np.concatenate((im_r,im_g, im_b), axis=1)
im_new =np.vstack((im_r,im_g, im_b))
n1=Image.fromarray(im_new)
n1.save("concat.jpg")
 
 

In [119]:
import os
def get_imlist(path):
    
    
    return [os.path.join(path,f) for f in os.listdir(path) if f.endswith('jpg')]

In [122]:
filelist=get_imlist("img/")

for infile in filelist:
    outfile=os.path.splitext(infile)[0]+".jpg"
    print(outfile)
    if infile != outfile:
        try:
            Image.open(infile).save(outfile)
        except IOError:
            print("cannot convert",infile)

img/1.jpg
img/1n.jpg
img/1nn.jpg
img/2.jpg
img/23.jpg
img/24.jpg
img/25.jpg
img/3.jpg
img/new.jpg
img/q.jpg
img/q3.jpg


In [123]:
im2=255-im


In [124]:
n1=Image.fromarray(im2)
n1.save("img/w.jpg")


In [127]:
print(im.shape)
print(im2.shape)
print(im4.shape)

(340, 600, 3)
(640, 1024, 3)
(900, 1600, 3)


In [129]:
im.resize(340,600,3)

im4.resize(340,600,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [133]:
im4.resize(340,600,3)

In [132]:
im2.resize(340,600,3)

In [134]:
im_news=np.concatenate((im,im2,im4),axis=1)
n1=Image.fromarray(im_news)
n1.save("img/new1.jpg")


## Image Reduction

In [143]:
#color reduction with loop
im = np.array(Image.open("img/1.jpg"))
im_3=im
im_5=im

for i in range(190):
    for j in range(250):
        im_3[i,j]=im[i,j]//92
        im_5[i,j]=im[i,j]//22
        
im_dec=np.concatenate((im,im_3,im_5),axis=1)    
Image.fromarray(im_dec).save("img/qwe.jpg")

In [144]:
#color reduction without loop
im = np.array(Image.open("img/1.jpg"))
im_3=im//92*92
im_5=im//158*158
im_dec=np.concatenate((im,im_3,im_5),axis=1)    
Image.fromarray(im_dec).save("img/qwe1.jpg")

In [149]:
im = np.array(Image.open("img/1.jpg").resize((256,256)))
im_3=im//92*92
im_5=im//158*158
im_dec=np.concatenate((im,im_3,im_5),axis=1)    
Image.fromarray(im_dec).save("img/qwe2.jpg")

In [150]:
im = np.array(Image.open("img/2.jpg").resize((256,256)))
im_3=im//92*92
im_5=im//158*158
im_dec=np.concatenate((im,im_3,im_5),axis=1)    
Image.fromarray(im_dec).save("img/qwe3.jpg")

## Image trim


In [153]:
im = np.array(Image.open("img/1.jpg"))
print(im.shape)

im_trim1=im[300:400,300:400]
print(im_trim1.shape)
Image.fromarray(im_trim1).save("img/1trim.jpg")

(640, 1024, 3)
(100, 100, 3)


In [156]:
def trim(array,x,y,w,h):
    return array[y:y+h,x:x+h]
print(im.shape)
im_trim2=trim(im,50,50,50,50)
print(im_trim2.shape)
Image.fromarray(im_trim1).save("img/1trim2.jpg")

(640, 1024, 3)
(50, 50, 3)


## Rotation


In [170]:
Image.fromarray(np.rot90(im)).save("img/1rot90.jpg")
Image.fromarray(np.rot90(im,2)).save("img/1rot180.jpg")
Image.fromarray(np.rot90(im,3)).save("img/1rot270.jpg")

## Spliting

In [159]:
im_0,im_1,im_2=np.array_split(im,3,axis=1)
print(im_0.shape)
print(im_1.shape)
print(im_2.shape)
Image.fromarray(im_0).save("img/10.jpg")
Image.fromarray(im_1).save("img/11.jpg")
Image.fromarray(im_2).save("img/12.jpg")

(640, 342, 3)
(640, 341, 3)
(640, 341, 3)


## Overlapping

In [165]:
im = np.array(Image.open("img/1.jpg"))
im1 = np.array(Image.open("img/2.jpg").resize(im.shape[1::-1],Image.BILINEAR))
print(im.dtype)
print(im1.dtype)
dst=im*0.5+im1*0.5
print(dst.dtype)

Image.fromarray(dst.astype(np.uint8)).save("img/after_blending.jpg")

uint8
uint8
float64


In [166]:
im = np.array(Image.open("img/1.jpg"))
im1 = np.array(Image.open("img/2.jpg").resize(im.shape[1::-1]))
print(im.dtype)
print(im1.dtype)
dst=im*0.5+im1*0.5
print(dst.dtype)

Image.fromarray(dst.astype(np.uint8)).save("img/after_blending1.jpg")

uint8
uint8
float64


## flip


In [175]:
Image.fromarray(np.flipud(im)).save("img/1ud.jpg")
Image.fromarray(np.fliplr(im)).save("img/1lr.jpg")
Image.fromarray(np.flipud(im)).save("img/1ud.jpg")

## Image pasting

In [182]:
img = Image.open("img/1.jpg")  
ds = (Image.open("img/2.jpg"))
ds.paste(img, (100, 200))
ds.save("img/pasted_picture.jpg")