In [3]:
import numpy as np
a = np.array([0,1, 2,3,4])

In [5]:
b = a[2:4] 
print(b)
b[0]=10
print(a)


[2 3]
[ 0  1 10  3  4]


In [18]:
curve_center =80
grades =np.array([72,35,64,88,51,90,74,12])

def curve(grades):
    average =grades.mean()
    print("average is" , average)
    change =curve_center - average
    #Vectorisation and broadcasting 
    # [72,35,64,88.....]+19.25,19.25,19.25......
    new_grades=grades+change
    print(new_grades)
    return np.clip(new_grades,grades,100)
    
    
curve(grades)



average is 60.75
[ 91.25  54.25  83.25 107.25  70.25 109.25  93.25  31.25]


array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [4]:
a=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
print(a[[0,2,5]])



[[ 0  1  2  3  4  5]
 [20 21 22 23 24 25]
 [50 51 52 53 54 55]]


In [21]:
#sum all the values of array
print(a.sum())
# sum col wise
print(a.sum(0))
#sum row wise
print(a.sum(1))

990


In [22]:
# sum col wise
print(a.sum(0))

[150 156 162 168 174 180]


In [24]:
#sum row wise
print(a.sum(1))

[ 15  75 135 195 255 315]


In [31]:
a=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
b=np.arange(0,6)
c=np.arange(10,16)
d=np.arange(20,26)
e=np.arange(30,36)
f=np.arange(40,46)
g=np.arange(50,56)


TypeError: Cannot construct a dtype from an array

In [3]:
import numpy as np
import time
a=np.arange(10)
print(a)
begin2=time.time()
d=np.take(a,([1,2,-1]))
print(d)
end2=time.time()
print("time is" ,end2-begin2)
# [0 1 2 3 4 5 6 7 8 9]
# [1 2 9]
# time is 0.0009975433349609375

[0 1 2 3 4 5 6 7 8 9]
[1 2 9]
time is 0.0009975433349609375


In [3]:
import numpy as np
import time
a=np.arange(10)
print(a)
begin1=time.time()
c=a[[1,2,-1]]
print(c)
end1=time.time()
print("time is" ,end1-begin1)
# [0 1 2 3 4 5 6 7 8 9]
# [1 2 9]
# time is 0.0010018348693847656

[0 1 2 3 4 5 6 7 8 9]
[1 2 9]
time is 0.0010275840759277344


In [ ]:
#diagonal


In [37]:
#add a row wise sum list  in array
a=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
x=a.sum(0)
print(x)
x=np.array(x)
print(x)
print(x.shape)
print(a.shape)
#a=np.append(a,np.array(x),axis=1)
r=np.vstack((a,x))
r



# ValueError: all the input arrays must have same number of dimensions,
# but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

[150 156 162 168 174 180]
[150 156 162 168 174 180]
(6,)
(6, 6)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [36]:
#add a col wise sum list  in array
a=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
x=a.sum(1)
print(x)
# x=np.array(x)
x = np.array(x)
x = x.reshape(6,1)
print(x.shape)
# print(a.shape)
a=np.append(a,np.array(x),axis=1)
print(a)
r=np.hstack((a,x))
r


# x = np.array(x)

# x = x.reshape(6,1)


[ 15  75 135 195 255 315]
(6, 1)
[[  0   1   2   3   4   5  15]
 [ 10  11  12  13  14  15  75]
 [ 20  21  22  23  24  25 135]
 [ 30  31  32  33  34  35 195]
 [ 40  41  42  43  44  45 255]
 [ 50  51  52  53  54  55 315]]


array([[  0,   1,   2,   3,   4,   5,  15,  15],
       [ 10,  11,  12,  13,  14,  15,  75,  75],
       [ 20,  21,  22,  23,  24,  25, 135, 135],
       [ 30,  31,  32,  33,  34,  35, 195, 195],
       [ 40,  41,  42,  43,  44,  45, 255, 255],
       [ 50,  51,  52,  53,  54,  55, 315, 315]])

In [ ]:
#generatee single dim array
#to add in verticalyy
#use transpose







#add a row wise sum list  in array
a=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
a=np.append(a,[np.sum(a,axis=0)],axis=0)
print(a)
#This calculates the column
col=np.array([np.sum(a,axis=1)])
print(a)
print("shape is ",col.shape)
#Finally we add the column
a=np.concatenate((a,col.T),axis=1)
print(a)

In [24]:
#transpose
rowsum=(a.sum(1))
print(rowsum.shape)
y=rowsum.transpose
c=np.array(y())
print(c)
print(c.shape)

(6,)
[ 15  75 135 195 255 315]
(6,)


In [74]:
#readung a file
import csv
spotify=np.genfromtxt("submission.csv", delimiter=",",skip_header=1)
print(spotify[0:8,])
print(spotify.shape)


[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]
 [6. 6.]
 [7. 7.]]
(1000, 2)


##Practice

In [28]:
a=np.array([[0, 1, 2],
[3, 4, 5],
[6, 7, 8]])
print(a)
np.hsplit(a, 3)
print(a.nbytes)
print(a.size)
print(a.itemsize)
print(a.ndim)

# [array([[0],
# [3],
# [6]]),
# array([[1],
# [4],
# [7]]),
# array([[2],
# [5],
# [8]])]



[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
9
4
2


In [ ]:
#5 by 4 array
n=5
k=4
a=np.zeros([n,k])
print(a)
for i in range(n):
    for j in range(k):
        a[i][j]=i+2*j
        
#rowwise colwise sum to be added
#This adds the row
a=np.append(a,[np.sum(a,axis=0)],axis=0)
#This calculates the column
col=np.array([np.sum(a,axis=1)])
print("shape is ",col.shape)
#Finally we add the column
a=np.concatenate((a,col.T),axis=1)
print(a)

### NP broadcasting

Alternative to broadcasting

In [32]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  


for i in range(4):
    y[i, :] = x[i, :] + v
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Using tiling

In [35]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   
print(vv)
y=x+vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [43]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
x = np.array([[1,2,3], [4,5,6]])
print(x + v)
print((x.T + w).T)


[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
