# Numpy Exercises


In [2]:
# Q1 Following is the provided numPy array. return array of items in the third column
# from all rows

# import numpy
# sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])


import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[:,2]

array([33, 66, 99])

In [7]:
# Q2 Add the following two NumPy arrays and Modify a result array by calculating the
# square of each element

# arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
# arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
result=arrayOne+arrayTwo
print(result)
result**2



[[20 39 33]
 [25 25 28]]


array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

In [36]:
# Q3 Sort following NumPy array

# sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
#  Sort by the second row and
#  Sort by the second column
#  Printing Original array
#  [[34 43 73]
#  [82 22 12]
#  [53 94 66]]
# 
#  Sorting Original array by secoond row
#  [[73 43 34]
#  [12 22 82]
#  [66 94 53]]
# 
#  Sorting Original array by secoond column
#  [[82 22 12]
#  [34 43 73]
#  [53 94 66]]
# 

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("\nSorting Original array by secoond row")
print(sortArrayByRow)

print("\nSorting Original array by secoond column")
sortArrayByColumn = sampleArray[sampleArray[:,1].argsort()]
print(sortArrayByColumn)

[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [13]:
# Q4 Following is the 2-D array. Print max from axis 0 and min from axis 1

# Import numpy
# sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])


import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray.max(axis=0))
print(numpy.amax(sampleArray,axis=0))
print(sampleArray.min(axis=1))
print(numpy.amin(sampleArray,axis=1))

[82 94 73]
[82 94 73]
[34 12 53]
[34 12 53]


In [17]:
# Q5  Following is the input NumPy array delete column two and insert following new
# column in its place.

# import numpy
# sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
# newColumn = numpy.array([[10,10,10]])


sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])
sampleArray=sampleArray[:,:2]
a=numpy.concatenate((sampleArray,newColumn.T),axis=1)
print(a)
        

[[34 43 10]
 [82 22 10]
 [53 94 10]]


In [37]:
# q6 How to add a border ((filled with 0's)) around an existing array OF 5 BY 5?
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)
np.pad?

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
# Q7 Create a 8x8 matrix and fill it with a checkerboard pattern
# x = np.ones((3,3))
# print("Checkerboard pattern:")
# print(x)
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [40]:
# Q8 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print (np.unravel_index(100, (6,7,8)))
# np.unravel_index?

(1, 5, 4)


In [28]:
# Q9 How to find common values between two arrays?
# Hint : Use intersect

array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))




Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]
Array1:  [  0 230  20 450  60]
Array2:  [10, 30, 40]
Common values between two arrays:
[]


In [30]:
# Q10 #How to get all the dates corresponding to the month of July 2016?
# Hint : Use datetime64 function

print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
