In [2]:
import numpy as np
sudoku = np.array([
[2, 8, 7, 1, 6, 5, 9, 4, 3],
[9, 5, 4, 7, 3, 2, 1, 6, 8],
[6, 1, 3, 8, 4, 9, 7, 5, 2],
[8, 7, 9, 6, 5, 1, 2, 3, 4],
[4, 2, 1, 3, 9, 8, 6, 7, 5],
[3, 6, 5, 4, 2, 7, 8, 9, 1],
[1, 9, 8, 5, 7, 3, 4, 2, 6],
[5, 4, 2, 9, 1, 6, 3, 8, 7],
[7, 3, 6, 2, 8, 4, 5, 1, 9]
])
shape = (3, 3, 3, 3)
strides = sudoku.itemsize * np.array([27, 3, 9, 1])
squares = np.lib.stride_tricks.as_strided(sudoku, shape=shape,
strides=strides)
print(squares)

[[[[2 8 7]
   [9 5 4]
   [6 1 3]]

  [[1 6 5]
   [7 3 2]
   [8 4 9]]

  [[9 4 3]
   [1 6 8]
   [7 5 2]]]


 [[[8 7 9]
   [4 2 1]
   [3 6 5]]

  [[6 5 1]
   [3 9 8]
   [4 2 7]]

  [[2 3 4]
   [6 7 5]
   [8 9 1]]]


 [[[1 9 8]
   [5 4 2]
   [7 3 6]]

  [[5 7 3]
   [9 1 6]
   [2 8 4]]

  [[4 2 6]
   [3 8 7]
   [5 1 9]]]]


In [4]:
msg = """ aaaaaaaaaaaaa
bbb'''bbbbbbbbbb""bbbbbbb'bbbb
cccccccccccccc"""
msg


' aaaaaaaaaaaaa\nbbb\'\'\'bbbbbbbbbb""bbbbbbb\'bbbb\ncccccccccccccc'

In [16]:
#add a row wise sum list  in array
a=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
a=np.append(a,[np.sum(a,axis=0)],axis=0)
print(a)
#This calculates the column
col=np.array([np.sum(a,axis=1)])
print(a)
print("shape is ",col.shape)
#Finally we add the column
a=np.concatenate((a,col.T),axis=1)
print(a)

[[  0   1   2   3   4   5]
 [ 10  11  12  13  14  15]
 [ 20  21  22  23  24  25]
 [ 30  31  32  33  34  35]
 [ 40  41  42  43  44  45]
 [ 50  51  52  53  54  55]
 [150 156 162 168 174 180]]
[[  0   1   2   3   4   5]
 [ 10  11  12  13  14  15]
 [ 20  21  22  23  24  25]
 [ 30  31  32  33  34  35]
 [ 40  41  42  43  44  45]
 [ 50  51  52  53  54  55]
 [150 156 162 168 174 180]]
shape is  (1, 7)
[[  0   1   2   3   4   5  15]
 [ 10  11  12  13  14  15  75]
 [ 20  21  22  23  24  25 135]
 [ 30  31  32  33  34  35 195]
 [ 40  41  42  43  44  45 255]
 [ 50  51  52  53  54  55 315]
 [150 156 162 168 174 180 990]]


In [ ]:
#5 by 4 array
n=5
k=4
a=np.zeros([n,k])
print(a)
for i in range(n):
    for j in range(k):
        a[i][j]=i+2*j
        
#rowwise colwise sum to be added
#This adds the row
a=np.append(a,[np.sum(a,axis=0)],axis=0)
#This calculates the column
col=np.array([np.sum(a,axis=1)])
print("shape is ",col.shape)
#Finally we add the column
a=np.concatenate((a,col.T),axis=1)
print(a)

In [48]:
x=np.random.rand(3,4)
print(x)
# [[0.98444724 0.41360892 0.7250693  0.39440123]
#  [0.46126023 0.11151939 0.95527915 0.76568655]
#  [0.29534511 0.25065745 0.21581712 0.62155136]]

[[0.44233709 0.81668584 0.47392122 0.14352003]
 [0.60249408 0.47694624 0.02950927 0.80675076]
 [0.69141826 0.75341697 0.2421303  0.95622329]]


In [14]:
import numpy as np
np.random.seed(0)
v=np.random.randint(2,200,10)
v

array([174,  49, 119, 194,  69, 197, 105,  11,  23,  38])

In [47]:
np.random.seed?

In [17]:
import numpy as np
np.random.seed(0)
v=np.random.randint(2,200,10)
v

array([174,  49, 119, 194,  69, 197, 105,  11,  23,  38])

In [ ]:
array([112, 158,  71, 168,  80,  21,  68, 145,   3,  66])

In [ ]:
# #You are given 5 cylindrical containers with different radius
# #and heights ranging between 5 and 25 cm. 
# #Find out
# Hint:
#     make a numpy array 10 random numbers generate 
#     reshape array 
#     separate radius array and height array use slicing(1 d arrays)
#     volume and sum
    
#     dot product
#     max... argmax    min argmin
    
#     mean...... make a list or tuple
    
# a) the volume of water that each container can contain,
# b) the total volume of water that all containers can contain,
# c) which container can hold the highest volume and how much,
# d) which container can hold the least volume and how much,
# e) what is the mean, median and standard deviation of the volumes 
# #of water that can be contained in the containers?

In [61]:
np.random.seed(0)
v=np.random.randint(5,25,10)
v=v.reshape(5,2)
print(v)


#radius and height
r = v[:,0]
h = v[:,1]
print(r)
print(h)


#individual volume
volume = np.pi*(r**2)*h
print(volume)


#total volume by function
total_volume = volume.sum()


#total volume by dot product
radius_squared = np.square(r)
dot_product = np.dot(radius_squared, h)
total_volume_by_dot_product = np.pi*dot_product

print(total_volume)
print(total_volume_by_dot_product)


#max volume
max_volume = volume.max()
index_of_max_volume = volume.argmax()
print(max_volume)
print(index_of_max_volume)


#min volume
min_volume = volume.min()
index_of_min_volume = volume.argmin()
print(min_volume)
print(index_of_min_volume)


#volume mean
volume_mean = np.mean(volume)
print(volume_mean)


#volume median
volume_median = np.median(volume)
print(volume_median)


#volume standard deviation
volume_standard_deviation = np.std(volume)
print(volume_standard_deviation)




[[17 20]
 [ 5  8]
 [ 8 12]
 [14 24]
 [23  9]]
[17  5  8 14 23]
[20  8 12 24  9]
[18158.40553775   628.31853072  2412.74315796 14778.05184249
 14957.12262374]
50934.64169265132
50934.64169265132
18158.405537749004
0
628.3185307179587
1
10186.928338530264
14778.051842486386
7199.758245451731


In [119]:
stats=[]
stats.append(volume_mean)
stats.append(volume_median)
stats.append(volume_standard_deviation)
stats

[10186.928338530264, 14778.051842486386, 7199.758245451731]


### Self Practice

In [71]:
# Create a random vector of size 30 and find the mean value
np.random.seed(0)
Z = np.random.random(10)
m = Z.mean()
print (m)

0.6157662833145425


In [79]:
#diagonal array
Z = np.diag(np.arange(1,6))
print (Z)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
#checkerboard using tile
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)



In [80]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [83]:
# Create a 5x5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [86]:
#  Consider a generator function that generates 10 integers and use it to build an array


def generate(): 
    for x in range(11):
        yield x
        
Z = np.fromiter(generate(), dtype=float, count=-1)
print (Z)



[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [89]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [93]:
# Consider two random array A anb B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)



False


In [100]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])



[[6 9 9]
 [7 6 9]
 [1 0 1]]
[[1 0 1]
 [7 6 9]
 [6 9 9]]


In [116]:
# Problem 2
# 25 cards numbered 1 through 25 are randomly distributed equally amongst 5 people. 
# Find the sum of cards for each person such that for the 1st person,
# the sum is the value of 1st card minus the sum of rest of the cards; 
# for the 2nd person, the sum is the value of 2nd card minus the sum of rest of the cards, 
# and so on. The person for whom the sum of the cards is greatest will be the winner. Find the winner.

numbers = np.arange(1,26)
print(numbers)


#shuffling
np.random.shuffle(numbers)
print(numbers)


#reshaping
reshaped_numbers = numbers.reshape(5,5)
print(reshaped_numbers)


#generate identity matrix
I = np.eye(5)
print(I)


#diagonal elements * identity
diagonal_matrix = np.multiply(reshaped_numbers,I)
print(diagonal_matrix)



U = np.ones((5,5))
I_minus_U = I - U
negative_diagonal_matrix = np.multiply(reshaped_numbers,I_minus_U)
print(negative_diagonal_matrix)


combined_matrix = np.add(diagonal_matrix, negative_diagonal_matrix)
print(combined_matrix)


sum_matrix = combined_matrix.sum(axis=1)
print(sum_matrix)



winner = np.argmax(sum_matrix)
print("winner is")
print(winner)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[21 19 23 13 20 25  3 24  2 16  4 18  8  5 15  1  7 12 11  9 14 10  6 17
 22]
[[21 19 23 13 20]
 [25  3 24  2 16]
 [ 4 18  8  5 15]
 [ 1  7 12 11  9]
 [14 10  6 17 22]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[21.  0.  0.  0.  0.]
 [ 0.  3.  0.  0.  0.]
 [ 0.  0.  8.  0.  0.]
 [ 0.  0.  0. 11.  0.]
 [ 0.  0.  0.  0. 22.]]
[[  0. -19. -23. -13. -20.]
 [-25.   0. -24.  -2. -16.]
 [ -4. -18.   0.  -5. -15.]
 [ -1.  -7. -12.   0.  -9.]
 [-14. -10.  -6. -17.   0.]]
[[ 21. -19. -23. -13. -20.]
 [-25.   3. -24.  -2. -16.]
 [ -4. -18.   8.  -5. -15.]
 [ -1.  -7. -12.  11.  -9.]
 [-14. -10.  -6. -17.  22.]]
[-54. -64. -34. -18. -25.]
winner is
3


In [117]:
# Problem 3
# You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.

# Solution 3
# We need to cut the rope at equidistant points such that there are 9 parts. So, besides the start and end points,
# we need 8 more points; a total of 10 points.


start = 0
end = 5
no_of_points = 10


np.linspace(start, end, no_of_points)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### CSV

In [ ]:
np.genfromtxt("winequality_red.csv", delimiter=",",skip_header=1)

In [118]:
import csv
wines=np.genfromtxt("wines\winequality-red.csv", delimiter=";",skip_header=1)
print(wines[0:3])


[[7.400e+00 7.000e-01 0.000e+00 1.900e+00 7.600e-02 1.100e+01 3.400e+01
  9.978e-01 3.510e+00 5.600e-01 9.400e+00 5.000e+00]
 [7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.800e+00 7.600e-01 4.000e-02 2.300e+00 9.200e-02 1.500e+01 5.400e+01
  9.970e-01 3.260e+00 6.500e-01 9.800e+00 5.000e+00]]
