# NUMPY

What is NumPy?<br>
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [4]:
import numpy

In [5]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [7]:
print(np.__version__)

1.19.2


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [10]:
arr = np.array(42)

print(arr)

42


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)
print(arr[0,0,0,0,3])




[[[[[1 2 3 4]]]]]
number of dimensions : 5
4


# Numpy starting By maam

In [20]:
import numpy as np

In [ ]:
# numpy
# pandas
# scipy
# scikit learn


# for data analytics
# numpy 
# pandas

# for ml/data science
# scikit learn

# dl/ml
# tensorflow

numpy deals basically with array


In [21]:
# we can import some part of library also as per our requirement
from numpy import arange
a=arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
# creating an array
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
print(type(a))
print(a[2])
print(a[2,2])
print(a.dtype)

(3, 3)
<class 'numpy.ndarray'>
[7 8 9]
9
int32


In [79]:
#slcing array is same as list, but here multiple arrays
print(a)

print(a[1])
print(a[1:])
print(a[1,1:])
print(a[:1,1:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[[4 5 6]
 [7 8 9]]
[5 6]
[[2 3]]


In [66]:
a=np.array(range(1,10))
b=np.array(range(1,900,100))
print(a)
print(b)
print(a*b)
print(a+b)
print(b-a)
print(b/a+1)

[1 2 3 4 5 6 7 8 9]
[  1 101 201 301 401 501 601 701 801]
[   1  202  603 1204 2005 3006 4207 5608 7209]
[  2 103 204 305 406 507 608 709 810]
[  0  99 198 297 396 495 594 693 792]
[ 2.         51.5        68.         76.25       81.2        84.5
 86.85714286 88.625      90.        ]


In [48]:
#initialisation of array with any integer
a.fill(0)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [80]:
a.itemsize

4

In [81]:
a.shape


(3, 3)

In [83]:
a[0]=10.6
print(a)

[[10 10 10]
 [ 4  5  6]
 [ 7  8  9]]


In [78]:
a.size

9

In [76]:
#same as a.fill but is very slow compared to a.fill
a[:]=1
print(a)

[1 1 1 1 1 1 1 1 1]


## Self Practice

In [156]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]
           ,[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a[(0,1,2,3,4),(1,2,3,4,5)]
print(a[[0,2,5]])

[[ 0  1  2  3  4  5]
 [20 21 22 23 24 25]
 [50 51 52 53 54 55]]


In [89]:
print(a[1::2,::3])
print(a[1::2,:4:3])
print(a[1,0])

[[10 13]
 [30 33]
 [50 53]]
[[10 13]
 [30 33]
 [50 53]]
10


In [138]:
x=[0,10,20,30,40,50,60,70,80]
x=np.array(x)
#[x[1],x[5],x[6]]
Ind=x[[1, 5, 6]]
print(Ind)

[10 50 60]


In [148]:
a = arange(0,80,10)
print(a)
y = a[[1, 2, -3]]
print(y)
x = np.take(a,[1,2,-3])
print(x)

[ 0 10 20 30 40 50 60 70]
[10 20 50]
[10 20 50]


In [150]:
mask = np.array([0,1,1,1,0,1,0,0], dtype=bool)
a=np.array([0,10,20,30,40,50,60,70])
y = a[mask]
f= np.compress(mask, a)
print(f)
print(y)


[10 20 30 50]
[10 20 30 50]


In [153]:
b=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
Row=np.array([0,1,2])
Col=np.array([2,1,3])
c=b[Row,Col]
print(c)
print(b.sum())
print(b.prod(axis=0))
print(b[1,(2,3)])

[ 2  5 11]
66
[  0  45 120 231]
[6 7]


In [132]:
np.random.rand(2,4)

array([[0.8015026 , 0.14712123, 0.87015485, 0.65111833],
       [0.30474885, 0.33505542, 0.97563246, 0.64211315]])

In [139]:
earnings = [
[ [500,505,490], [810,450,678], [234,897,430], [560,1023,640] ],
[ [600,605,490], [345,900,1000], [780,730,710], [670,540,324] ]
]

earnings = np.array(earnings)
print(earnings[0,0,0])
print(earnings.shape)

500
(2, 4, 3)


https://numpy.org/doc/stable/user/basics.creation.html

In [140]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [141]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [142]:
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [159]:
x = np.arange(27).reshape((3,3,3))
print(x)
print("1")
print(np.sum(x,axis=0))
print("2")
print(x.sum(axis=0))
x.sum(0), x.sum(1), x.sum(2),x.sum(-1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
1
[[27 30 33]
 [36 39 42]
 [45 48 51]]
2
[[27 30 33]
 [36 39 42]
 [45 48 51]]


(array([[27, 30, 33],
        [36, 39, 42],
        [45, 48, 51]]),
 array([[ 9, 12, 15],
        [36, 39, 42],
        [63, 66, 69]]),
 array([[ 3, 12, 21],
        [30, 39, 48],
        [57, 66, 75]]),
 array([[ 3, 12, 21],
        [30, 39, 48],
        [57, 66, 75]]))

The most basic task that can be done with the nditer is to visit every element of an array.<br>
Each element is provided one by one using the standard Python iterator interface.

In [147]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a):
    print(x, end=' ')

0 1 2 3 4 5 

In [1]:
import numpy as np

In [4]:
np.random?

In [5]:
pwd

'C:\\Users\\hp\\python'

In [7]:
ls

 Volume in drive C has no label.
 Volume Serial Number is DE60-73D4

 Directory of C:\Users\hp\python

09-03-2021  08:03    <DIR>          .
09-03-2021  08:03    <DIR>          ..
09-03-2021  08:03    <DIR>          .ipynb_checkpoints
25-02-2021  10:59            32,810 imagesinnumpy.ipynb
26-02-2021  09:07           381,589 imagesinnumpy1.ipynb
15-02-2021  11:30            32,652 NIELIT Assignment 5-checkpoint.ipynb
23-02-2021  19:55            59,934 NIELIT Module 2 (Data Science).1-checkpoint.ipynb
06-02-2021  15:17             2,690 number game.ipynb
26-02-2021  08:56            48,861 Numpy practical examples.ipynb
26-02-2021  12:34            79,398 numpy_basic3.ipynb
09-03-2021  08:03            17,161 Numpy_basics.ipynb
22-02-2021  11:17            18,574 Numpy_basics1.ipynb
23-02-2021  10:09            19,500 numpy_basics2.ipynb
24-02-2021  08:43             9,187 numpyassign1.ipynb
26-02-2021  08:36           315,381 prog1.ipynb
05-02-2021  09:20            13,432 pyhtonbasic

In [12]:
print("Did you know that 'word' is a word?")
print('did you know that \'word\' is a word?')

Did you know that 'word' is a word?
did you know that 'word' is a word?


'105'